### ISSUE TITLE
events.js:187 throw er; Unhandled 'error' event

### ISSUE THREAD

**Issue by JoffreyN** [takayama-lily/onebot#1]
C:\Users\zp\mystuff\onebot>node main 1101170736
[2020-09-25T15:21:33.221] [INFO] [SYSTEM] - OICQ程序启动。当前内核版本：v1.7.2
[2020-09-25T15:21:33.253] [INFO] [SYSTEM] - 已加载配置文件：
{
  platform: 2,
  kickoff: false,
  ignore_self: true,
  web_image_timeout: 30,
  web_record_timeout: 30,
  debug: false,
  host: '0.0.0.0',
  port: 5700,
  use_http: true,
  use_ws: false,
  access_token: '',
  secret: '',
  post_timeout: 30,
  post_message_format: 'string',
  enable_heartbeat: false,
  heartbeat_interval: 15000,
  post_url: [ 'http://127.0.0.1:8081' ],
  ws_reverse_url: [ 'ws://127.0.0.1:8082' ],
  ws_reverse_reconnect_interval: 3000,
  event_filter: ''
}
[2020-09-25T15:21:33.297] [INFO] [SYSTEM] - 开启http服务器成功，监听0.0.0.0:5700
[2020-09-25T15:21:34.298] [INFO] [BOT:1101170736] - connecting to msfwifi.3g.qq.com:8080
[2020-09-25T15:21:34.347] [INFO] [BOT:1101170736] - 113.96.12.224:8080 connected
events.js:187
      throw er; // Unhandled 'error' event
      ^

TypeError [ERR_INVALID_ARG_TYPE]: The "chunk" argument must be one of type string, Buffer, or Uint8Array. Received type number
    at chunkInvalid (_stream_readable.js:329:12)
    at readableAddChunk (_stream_readable.js:261:12)
    at Readable.push (_stream_readable.js:224:10)
    at next (internal/streams/from.js:34:27)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
Emitted 'error' event on Readable instance at:
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  code: 'ERR_INVALID_ARG_TYPE'
}

**Comment by JoffreyN** [comment]
C:\Users\zp\mystuff\onebot>node -v
v12.14.0

**Comment by takayama-lily** [comment]
node版本必须>=12.16

**Comment by JoffreyN** [comment]
谢谢，升级node后成功了
