### ISSUE TITLE
WebSocket 鉴权失败返回错误码时报错退出

### ISSUE THREAD

**Issue by Steve-xmh** [takayama-lily/onebot#36]
错误报告如下，应该是 `ws` 库因为错误码不合法抛出了一个错误：
```
C:\Path\To\onebot\node_modules\ws\lib\sender.js:112
      throw new TypeError('First argument must be a valid error code number');
      ^

TypeError: First argument must be a valid error code number
    at Sender.close (C:\Path\To\onebot\node_modules\ws\lib\sender.js:112:13)
    at WebSocket.close (C:\Path\To\onebot\node_modules\ws\lib\websocket.js:233:18)
    at WebSocketServer.<anonymous> (C:\Path\To\onebot\lib\core.js:248:31)
    at WebSocketServer.emit (events.js:315:20)
    at WebSocketServer.completeUpgrade (C:\Path\To\onebot\node_modules\ws\lib\websocket-server.js:330:5)
    at WebSocketServer.handleUpgrade (C:\Path\To\onebot\node_modules\ws\lib\websocket-server.js:246:10)
    at Server.upgrade (C:\Path\To\onebot\node_modules\ws\lib\websocket-server.js:92:16)
    at Server.emit (events.js:315:20)
    at onParserExecuteCommon (_http_server.js:695:14)
    at onParserExecute (_http_server.js:608:3)
```

重现步骤：在配置里添加 `access_token` 字段，然后使用任意的客户端连接（token 故意设置不正确）（我使用了自己的 `oneui`），然后报错退出。

这个问题有可能会影响到服务器的运行，别人可以使用这个方式来强制关闭后端。

**Comment by takayama-lily** [comment]
谢谢指出，
